# frontend/app.yaml
runtime: nodejs18
env: standard

service: frontend

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: "https://your-backend-service-url"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_Z3Jvd2luZy1zdGluZ3JheS0xNy5jbGVyay5hY2NvdW50cy5kZXYk"
  CLERK_SECRET_KEY: "sk_test_SXpmibrgotxAWhYftmeVR78jGsGuspRfqwrALJmoDN"
