

services:
  db:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db ok' | nc localhost 27017 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '3001:3001'
    volumes:
      # Only mount the source code, not node_modules.
      - ./backend:/app
      - /app/node_modules/bcrypt/
    command: yarn start:dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: yarn dev
    depends_on:
      - backend

volumes:
  mongo-data:
